version: "2.1"
services:
  plex:
    image: ghcr.io/linuxserver/plex:arm32v7-latest 
    container_name: plex
    network_mode: host
    environment:
      - PUID=1001
      - PGID=100
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /media/drive1/docker/plex:/config
      - /media/drive1/TV:/tv
      - /media/drive1/Movies:/movies
      - /media/drive1/Music:/music
    restart: unless-stopped
