version: "2.1"
services:
  paperless-ng:
    image: lscr.io/linuxserver/paperless-ng:latest
    container_name: paperless-ng
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - REDIS_URL= #optional
    volumes:
      - /media/drive1/docker/paperless/config:/config
      - /media/drive1/docker/paperless/:/data
    ports:
      - 8000:8000
    restart: unless-stopped
