version: '3'

services:
  portainer:
    image: jlesage/filezilla:latest
    container_name: filezilla
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /media/drive1/docker/filezilla:/config:rw
      - /media/drive1:/storage:rw
    ports:
      - 5800:5800
